plugins:
  - prettier-plugin-css-order
cssDeclarationSorterOrder: smacss
overrides:
  - files:
      - "*.jsonc"
      - devcontainer.json
      - jsconfig.json
      - language-configuration.json
      - tsconfig.json
    options:
      #  Use one of the following options
      parser: json
      trailingComma: none
